### ISSUE TITLE
Landing page: vertical scrolling causes text to overlap over the top frame menus

### ISSUE THREAD

**Issue by jordigilh** [rhdhorchestrator/rhdhorchestrator.github.io#63]
Steps to reproduce:
* Load the landing page (https://www.parodos.dev/)
* Resize the browser window to be smaller than the contents of the page, so that the vertical scroll bar appears, preferably resize to show only 3/5 of the screen contents
* Scroll down so that the text "Orchestrating Systems | Migrating Code Infrastructure | ..." reaches the top of the window frame.

Actual result:
* Text "Orchestrating Systems | Migrating | ..." overlaps with the page top frame menus

Expected result:
* Text "Orchestrating Systems | Migrating | ..." does not overlap.
![Screenshot 2024-04-12 at 3 41 32 PM](https://github.com/parodos-dev/parodos-dev.github.io/assets/19480463/d540f3fa-898c-4864-93e0-6ddc083f3eee)

**Comment by masayag** [comment]
Closing since this seems to be already fixed.
